vcom -work ieee_proposed ./fixed_proposed/fixed_types.vhd
vcom -work ieee_proposed ./fixed_proposed/fixed_pkg_c.vhd

vcom -work work mem_types.vhd
vcom -work work ./Min_Sum/CNPU/Mod2/CNU/CNP/src/cnp.vhd
vcom -work work ./Min_Sum/CNPU/Mod2/CNU/CNP/src/full_comp.vhd
vcom -work work ./Min_Sum/CNPU/Mod2/CNU/CNP/src/semi_comp.vhd
vcom -work work ./Min_Sum/CNPU/Mod2/CNU/CNP/src/signe.vhd
vcom -work work ./Min_Sum/CNPU/Mod2/CNU/CNP/src/sw.vhd
vcom -work work ./Min_Sum/CNPU/Mod2/CNU/CNP/src/TOP_cnp.vhd
vcom -work work ./Min_Sum/CNPU/Mod2/CNU/CNU_TOP/src/CNU.vhd
vcom -work work ./Min_Sum/CNPU/Mod2/CNU/CNU_TOP/src/prod_final.vhd
vcom -work work ./Min_Sum/CNPU/Mod2/CNU/output_selector/src/add19.vhd
vcom -work work ./Min_Sum/CNPU/Mod2/CNU/output_selector/src/mapping.vhd
vcom -work work ./Min_Sum/CNPU/Mod2/CNU/output_selector/src/mul.vhd
vcom -work work ./Min_Sum/CNPU/Mod2/CNU/output_selector/src/output_selector.vhd
vcom -work work ./Memories/2-inter_mem/Mem_U/1-Mem_Lock/src/lock.vhd
vcom -work work ./Memories/2-inter_mem/MUX/Mem_Demux_1v6/src/mem_demux_1v6.vhd
vcom -work work ./Memories/2-inter_mem/MUX/Mem_Mux_6v1/src/Add13.vhd
vcom -work work ./Memories/2-inter_mem/MUX/Mem_Mux_6v1/src/concatenate.vhd
vcom -work work ./Memories/2-inter_mem/MUX/Mem_Mux_6v1/src/mem_mux_6v1.vhd
vcom -work work ./Min_Sum/CNPU/Mod1/Layer_Switch/src/switch_layer.vhd
vcom -work work ./Min_Sum/CNPU/Mod1/Mux_6V1/src/Add13.vhd
vcom -work work ./Min_Sum/CNPU/Mod1/Mux_6V1/src/Mulp.vhd
vcom -work work ./Min_Sum/CNPU/Mod1/Mux_6V1/src/Mux6v1.vhd
vcom -work work ./Min_Sum/CNPU/Mod1/sw_mux/src/mod1.vhd
vcom -work work ./Memories/1-CW_gen_Memory/CW_gen_Mem/src/code_gen_mem.vhd
vcom -work work ./Memories/1-CW_gen_Memory/Layer_Memory/src/Layer_mem.vhd
vcom -work work ./Memories/1-CW_gen_Memory/Switch/src/switch_mem.vhd
vcom -work work ./Memories/2-inter_mem/inter_mem/src/Top_intern_Mem.vhd
vcom -work work ./Memories/2-inter_mem/Mem_U/src/mem_u.vhd
vcom -work work ./Min_Sum/CNPU/Mod2/src/mod2.vhd
vcom -work work ./Min_Sum/VN_APLLR/AP_LLR/src/add_clmn.vhd
vcom -work work ./Min_Sum/VN_APLLR/AP_LLR/src/add.vhd
vcom -work work ./Min_Sum/VN_APLLR/AP_LLR/src/Ap_LLR.vhd
vcom -work work ./Min_Sum/VN_APLLR/VN/src/sous_clmn.vhd
vcom -work work ./Min_Sum/VN_APLLR/VN/src/sous.vhd
vcom -work work ./Min_Sum/VN_APLLR/VN/src/VN.vhd
vcom -work work ./Memories/2-inter_mem/MUX/Mulp_gen.vhd
vcom -work work ./Min_Sum/CNPU/src/CNPU.vhd
vcom -work work ./Memories/src/Memories.vhd
vcom -work work ./conversion_blocks/bound.vhd
vcom -work work ./conversion_blocks/conv_T2Tb.vhd
vcom -work work ./conversion_blocks/down_up.vhd
vcom -work work ./conversion_blocks/up_down.vhd
vcom -work work ./Read_blocks/barrel_shifter_rd.vhd
vcom -work work ./Read_blocks/control_filter_19.vhd
vcom -work work ./Read_blocks/inter_10.vhd
vcom -work work ./Read_blocks/inter_19.vhd
vcom -work work ./Read_blocks/inter_3.vhd
vcom -work work ./Read_blocks/inter_7.vhd
vcom -work work ./Read_blocks/inter_8.vhd
vcom -work work ./Read_blocks/inter_9.vhd
vcom -work work ./Read_blocks/inter_rd_top.vhd
vcom -work work ./Read_blocks/top_glob_rd.vhd
vcom -work work ./Read_blocks/top_rd.vhd
vcom -work work ./Write_blocks/barrel_wt.vhd
vcom -work work ./Write_blocks/inter_wt_10.vhd
vcom -work work ./Write_blocks/inter_wt_19.vhd
vcom -work work ./Write_blocks/inter_wt_3.vhd
vcom -work work ./Write_blocks/inter_wt_7.vhd
vcom -work work ./Write_blocks/inter_wt_8.vhd
vcom -work work ./Write_blocks/inter_wt_9.vhd
vcom -work work ./Write_blocks/inter_wt.vhd
vcom -work work ./Write_blocks/top_wt.vhd
vcom -work work ./TOP/TOP.vhd
vcom -work work ./TOP/TOP_tb.vhd

vsim work.TOP_tb
do wave.do
run 7443ns